'use strict';

const { ZigBeeDriver } = require('homey-zigbeedriver');

class ButtonWireless4Driver extends ZigBeeDriver {

  async onInit() {
    this.log('ButtonWireless4Driver initialized');
    
    // Flow cards are auto-generated by homey app build
    // No manual registration needed
  }
}

module.exports = ButtonWireless4Driver;
