'use strict';

const { ZigBeeDriver } = require('homey-zigbeedriver');

class UsbOutlet3gangDriver extends ZigBeeDriver {

  async onInit() {
    this.log('UsbOutlet3gangDriver initialized');
    
    // Flow cards are auto-generated by homey app build
    // No manual registration needed
  }
}

module.exports = UsbOutlet3gangDriver;
