'use strict';

const { ZigBeeDriver } = require('homey-zigbeedriver');

class UsbOutlet1gangDriver extends ZigBeeDriver {

  async onInit() {
    this.log('UsbOutlet1gangDriver initialized');
    
    // Flow cards are auto-generated by homey app build
    // No manual registration needed
  }
}

module.exports = UsbOutlet1gangDriver;
