// Auto-generated by tools/ci/generate-flow-handlers.js — review before commit.
'use strict';

const { Driver } = require('homey');

class UniversalZigbeeDriver extends Driver {

  async onInit() {
    await super.onInit();
    if (this._flowCardsRegistered) return;
    this._flowCardsRegistered = true;

      // === AUTO-GENERATED FLOW HANDLERS ===
      // Generated by tools/ci/generate-flow-handlers.js
      // Edit if you need custom behaviour.

      this.homey.flow.getConditionCard('universal_zigbee_thermostat_mode_is')?.registerRunListener(async (args) => {
        if (!args.device) return false;
        return true; // TODO: implement condition for universal_zigbee_thermostat_mode_is
      });
      this.homey.flow.getActionCard('universal_zigbee_turn_on')?.registerRunListener(async (args) => {
        if (!args.device) return false;
        await args.device.setCapabilityValue('onoff', true).catch(() => {});
        return true;
      });
      this.homey.flow.getActionCard('universal_zigbee_turn_off')?.registerRunListener(async (args) => {
        if (!args.device) return false;
        await args.device.setCapabilityValue('onoff', false).catch(() => {});
        return true;
      });
      this.homey.flow.getActionCard('universal_zigbee_toggle')?.registerRunListener(async (args) => {
        if (!args.device) return false;
        const v = args.device.getCapabilityValue('onoff');
        await args.device.setCapabilityValue('onoff', !v).catch(() => {});
        return true;
      });
      this.homey.flow.getActionCard('universal_zigbee_set_brightness')?.registerRunListener(async (args) => {
        if (!args.device) return false;
        await args.device.setCapabilityValue('brightness', args.brightness).catch(() => {});
        return true;
      });
      this.homey.flow.getActionCard('universal_zigbee_set_position')?.registerRunListener(async (args) => {
        if (!args.device) return false;
        await args.device.setCapabilityValue('onoff', true).catch(() => {});
        return true;
      });
      this.homey.flow.getActionCard('universal_zigbee_set_thermostat_mode')?.registerRunListener(async (args) => {
        if (!args.device) return false;
        await args.device.setCapabilityValue('thermostat_mode', args.mode).catch(() => {});
        return true;
      });
  }
}

module.exports = UniversalZigbeeDriver;
