const fs = require('fs');
const path = require('path');
const target = path.join(__dirname, 'crawl-blakadder.js');

const L = [];
L.push('#!/usr/bin/env node');
L.push('/**');
L.push(' * Blakadder Zigbee Device Database Crawler');
L.push(' * Fetches zigbee.blakadder.com/all.json — comprehensive Zigbee DB');
L.push(' * Extracts all Tuya fingerprints with rich metadata');
L.push(' * Run: node scripts/sync/crawl-blakadder.js');
L.push(' */');
L.push('const { fetchJSON } = require("./lib/fetch");');
L.push('const fs = require("fs");');
L.push('const path = require("path");');
L.push('');
L.push('const URL = "https://zigbee.blakadder.com/all.json";');
L.push('const OUT = path.join(__dirname, "data");');
L.push('');
L.push('const TUYA_MFR = /^(_TZ[A-Z0-9]{1,5}_[a-zA-Z0-9]+|_TYST1[12]_[a-zA-Z0-9]+|TUYATEC[a-zA-Z0-9_-]*)$/;');
L.push('');
L.push('async function crawlBlakadder() {');
L.push('  console.log("[BLAKADDER] Fetching all.json...");');
L.push('  const data = await fetchJSON(URL);');
L.push('  // data is array of device objects or object keyed by model');
L.push('  const devices = Array.isArray(data) ? data : Object.values(data);');
L.push('  console.log("[BLAKADDER] " + devices.length + " total devices in DB");');
L.push('');
L.push('  const fps = new Map();');
L.push('  for (const dev of devices) {');
L.push('    // Blakadder fields: manufacturerName, modelID, manufacturer, model, description, category');
L.push('    const mfr = dev.manufacturerName || dev.zigbeeManufacturer || dev.tuya_id || null;');
L.push('    const pid = dev.modelID || dev.zigbeeModel || null;');
L.push('    if (!mfr || !TUYA_MFR.test(mfr)) continue;');
L.push('    const k = mfr.toLowerCase();');
L.push('    if (fps.has(k)) continue;');
L.push('    fps.set(k, {');
L.push('      mfr,');
L.push('      productId: pid,');
L.push('      model: dev.model || dev.name || null,');
L.push('      description: dev.description || dev.category || null,');
L.push('      vendor: dev.manufacturer || dev.brand || null,');
L.push('      category: dev.category || null,');
L.push('      z2m: dev.z2m === true || dev.z2m === "true",');
L.push('      zha: dev.zha === true || dev.zha === "true",');
L.push('      deconz: dev.deconz === true || dev.deconz === "true",');
L.push('      source: "blakadder",');
L.push('    });');
L.push('  }');
L.push('');
L.push('  const result = {');
L.push('    date: new Date().toISOString(),');
L.push('    source: "zigbee.blakadder.com/all.json",');
L.push('    totalDevices: devices.length,');
L.push('    uniqueFingerprints: fps.size,');
L.push('    fingerprints: [...fps.values()],');
L.push('  };');
L.push('  fs.mkdirSync(OUT, { recursive: true });');
L.push('  fs.writeFileSync(path.join(OUT, "blakadder.json"), JSON.stringify(result, null, 2));');
L.push('  console.log("[BLAKADDER] " + fps.size + " unique Tuya fingerprints");');
L.push('  return result;');
L.push('}');
L.push('');
L.push('module.exports = crawlBlakadder;');
L.push('if (require.main === module) crawlBlakadder().catch(e => { console.error("[BLAKADDER] Error:", e.message); process.exit(1); });');

fs.writeFileSync(target, L.join('\n'));
console.log('Written crawl-blakadder.js:', L.length, 'lines');
