const fs = require('fs');
const path = require('path');
const target = path.join(__dirname, 'crawl-z2m.js');

const L = [];
L.push('#!/usr/bin/env node');
L.push('/**');
L.push(' * Live Z2M FULL Zigbee Fingerprint Crawler');
L.push(' * Scans ALL 366 device files in zigbee-herdsman-converters');
L.push(' * Extracts every Tuya fingerprint (_TZ*, _TZE*, _TYST11*, TUYATEC*)');
L.push(' * Run: node scripts/sync/crawl-z2m.js');
L.push(' */');
L.push('const { fetch, fetchJSON } = require("./lib/fetch");');
L.push('const fs = require("fs");');
L.push('const path = require("path");');
L.push('');
L.push('const API = "https://api.github.com/repos/Koenkk/zigbee-herdsman-converters/contents/src/devices";');
L.push('const RAW = "https://raw.githubusercontent.com/Koenkk/zigbee-herdsman-converters/master/src/devices/";');
L.push('const OUT = path.join(__dirname, "data");');
L.push('');
L.push('const TUYA_MFR = /^(_TZ[A-Z0-9]{1,5}_[a-zA-Z0-9]+|_TYST1[12]_[a-zA-Z0-9]+|TUYATEC[a-zA-Z0-9_-]*)$/;');
L.push('');
L.push('function parseFile(src, filename) {');
L.push('  const fps = new Map();');
L.push('  const lines = src.split("\\n");');
L.push('  let model = null, desc = null, vendor = null;');
L.push('');
L.push('  for (let i = 0; i < lines.length; i++) {');
L.push('    const line = lines[i];');
L.push('    const mm = line.match(/^\\s+model:\\s*[\'"]([^\'"]+)[\'"]/);');
L.push('    if (mm) model = mm[1];');
L.push('    const dm = line.match(/description:\\s*[\'"]([^\'"]+)[\'"]/);');
L.push('    if (dm) desc = dm[1];');
L.push('    const vm = line.match(/vendor:\\s*[\'"]([^\'"]+)[\'"]/);');
L.push('    if (vm) vendor = vm[1];');
L.push('');
L.push('    // P1: tuya.fingerprint("PID", ["mfr1", ...])');
L.push('    const fp1 = line.match(/tuya\\.fingerprint\\s*\\(\\s*[\'"]([^\'"]+)[\'"]\\s*,\\s*\\[([^\\]]+)\\]/);');
L.push('    if (fp1) {');
L.push('      const pid = fp1[1];');
L.push('      const mfrs = [...fp1[2].matchAll(/[\'"]([^\'"]+)[\'"]/g)].map(m => m[1]);');
L.push('      for (const mfr of mfrs) {');
L.push('        if (TUYA_MFR.test(mfr)) {');
L.push('          const k = mfr.toLowerCase();');
L.push('          if (!fps.has(k)) fps.set(k, { mfr, productId: pid, model, description: desc, vendor, file: filename, source: "z2m" });');
L.push('        }');
L.push('      }');
L.push('      continue;');
L.push('    }');
L.push('');
L.push('    // P2: manufacturerName: "xxx" in fingerprint blocks');
L.push('    const fp2 = line.match(/manufacturerName:\\s*[\'"]([^\'"]+)[\'"]/);');
L.push('    if (fp2 && TUYA_MFR.test(fp2[1])) {');
L.push('      const mfr = fp2[1];');
L.push('      const ctx = lines.slice(Math.max(0,i-3), i+3).join(" ");');
L.push('      const pidM = ctx.match(/modelID:\\s*[\'"]([^\'"]+)[\'"]/);');
L.push('      const k = mfr.toLowerCase();');
L.push('      if (!fps.has(k)) fps.set(k, { mfr, productId: pidM?pidM[1]:null, model, description: desc, vendor, file: filename, source: "z2m" });');
L.push('      continue;');
L.push('    }');
L.push('');
L.push('    // P3: tuya.whitelabel("V","M","D",["mfr",...])');
L.push('    const fp3 = line.match(/tuya\\.whitelabel\\s*\\(\\s*[\'"]([^\'"]+)[\'"]\\s*,\\s*[\'"]([^\'"]+)[\'"]\\s*,\\s*[\'"]([^\'"]+)[\'"]\\s*,\\s*\\[([^\\]]+)\\]/);');
L.push('    if (fp3) {');
L.push('      const mfrs = [...fp3[4].matchAll(/[\'"]([^\'"]+)[\'"]/g)].map(m => m[1]);');
L.push('      for (const mfr of mfrs) {');
L.push('        if (TUYA_MFR.test(mfr)) {');
L.push('          const k = mfr.toLowerCase();');
L.push('          if (!fps.has(k)) fps.set(k, { mfr, productId: model, model: fp3[2], description: fp3[3], vendor: fp3[1], file: filename, source: "z2m" });');
L.push('        }');
L.push('      }');
L.push('      continue;');
L.push('    }');
L.push('');
L.push('    // P4: zigbeeModel: ["xxx"] or fingerprint with Tuya mfr');
L.push('    const allMfrs = [...line.matchAll(/[\'"](_TZ[A-Z0-9]{1,5}_[a-zA-Z0-9]+|_TYST1[12]_[a-zA-Z0-9]+|TUYATEC[a-zA-Z0-9_-]+)[\'"]/g)];');
L.push('    for (const m of allMfrs) {');
L.push('      const k = m[1].toLowerCase();');
L.push('      if (!fps.has(k)) fps.set(k, { mfr: m[1], productId: null, model, description: desc, vendor, file: filename, source: "z2m" });');
L.push('    }');
L.push('  }');
L.push('  return fps;');
L.push('}');
L.push('');
L.push('async function crawlZ2M() {');
L.push('  console.log("[Z2M] Listing ALL device files...");');
L.push('  let fileList;');
L.push('  try {');
L.push('    fileList = await fetchJSON(API);');
L.push('  } catch (e) {');
L.push('    console.log("[Z2M] API failed, falling back to tuya.ts only");');
L.push('    fileList = [{ name: "tuya.ts", download_url: RAW + "tuya.ts" }];');
L.push('  }');
L.push('  const tsFiles = fileList.filter(f => f.name.endsWith(".ts") && f.name !== "index.ts");');
L.push('  console.log("[Z2M] " + tsFiles.length + " device files to scan");');
L.push('');
L.push('  const allFps = new Map();');
L.push('  let scanned = 0, errors = 0;');
L.push('  // Process in batches of 5');
L.push('  for (let i = 0; i < tsFiles.length; i += 5) {');
L.push('    const batch = tsFiles.slice(i, i + 5);');
L.push('    const results = await Promise.allSettled(batch.map(async f => {');
L.push('      const url = f.download_url || (RAW + f.name);');
L.push('      const src = await fetch(url);');
L.push('      return { name: f.name, fps: parseFile(src, f.name) };');
L.push('    }));');
L.push('    for (const r of results) {');
L.push('      if (r.status === "fulfilled") {');
L.push('        scanned++;');
L.push('        for (const [k, v] of r.value.fps) {');
L.push('          if (!allFps.has(k)) allFps.set(k, v);');
L.push('        }');
L.push('      } else { errors++; }');
L.push('    }');
L.push('    if ((i + 5) % 50 === 0 || i + 5 >= tsFiles.length) {');
L.push('      console.log("[Z2M]   " + Math.min(i+5, tsFiles.length) + "/" + tsFiles.length + " files, " + allFps.size + " fps so far");');
L.push('    }');
L.push('  }');
L.push('');
L.push('  const fps = [...allFps.values()];');
L.push('  fs.mkdirSync(OUT, { recursive: true });');
L.push('  const result = { date: new Date().toISOString(), source: "zigbee-herdsman-converters (ALL files)", filesScanned: scanned, errors, uniqueFingerprints: fps.length, fingerprints: fps };');
L.push('  fs.writeFileSync(path.join(OUT, "z2m.json"), JSON.stringify(result, null, 2));');
L.push('  console.log("[Z2M] " + scanned + " files scanned, " + fps.length + " unique Tuya fingerprints");');
L.push('  return result;');
L.push('}');
L.push('');
L.push('module.exports = crawlZ2M;');
L.push('if (require.main === module) crawlZ2M().catch(e => { console.error("[Z2M] Error:", e.message); process.exit(1); });');

fs.writeFileSync(target, L.join('\n'));
console.log('Rewritten crawl-z2m.js:', L.length, 'lines');
