const fs = require('fs');
const path = require('path');
const target = path.join(__dirname, 'crawl-zha.js');

const L = [];
L.push('#!/usr/bin/env node');
L.push('/**');
L.push(' * Live ZHA FULL Quirks Crawler');
L.push(' * Scans ALL quirks directories (not just tuya/) for Tuya fingerprints');
L.push(' * Run: node scripts/sync/crawl-zha.js');
L.push(' */');
L.push('const { fetch, fetchJSON } = require("./lib/fetch");');
L.push('const fs = require("fs");');
L.push('const path = require("path");');
L.push('');
L.push('const API_BASE = "https://api.github.com/repos/zigpy/zha-device-handlers/contents/zhaquirks";');
L.push('const RAW_BASE = "https://raw.githubusercontent.com/zigpy/zha-device-handlers/dev/zhaquirks/";');
L.push('const OUT = path.join(__dirname, "data");');
L.push('');
L.push('const TUYA_MFR = /(_TZ[A-Z0-9]{1,5}_[a-zA-Z0-9]+|_TYST1[12]_[a-zA-Z0-9]+|TUYATEC[a-zA-Z0-9_-]+)/;');
L.push('');
L.push('function parseQuirksFile(src, filepath) {');
L.push('  const fps = [];');
L.push('  // P1: MODELS_INFO tuples ("mfr", "pid")');
L.push('  const tuples = [...src.matchAll(/\\(\\s*["\']([^"\']+)["\']\\s*,\\s*["\']([^"\']+)["\']\\s*\\)/g)];');
L.push('  for (const m of tuples) {');
L.push('    if (TUYA_MFR.test(m[1])) fps.push({ mfr: m[1], productId: m[2], file: filepath, source: "zha" });');
L.push('  }');
L.push('  // P2: manufacturer = / model =');
L.push('  const mfrLines = [...src.matchAll(/manufacturer\\s*[:=]\\s*["\']([^"\']+)["\']/g)];');
L.push('  for (const m of mfrLines) {');
L.push('    if (TUYA_MFR.test(m[1]) && !fps.find(f => f.mfr === m[1])) {');
L.push('      fps.push({ mfr: m[1], productId: null, file: filepath, source: "zha" });');
L.push('    }');
L.push('  }');
L.push('  // P3: .applies_to("mfr", "pid")');
L.push('  const applies = [...src.matchAll(/\\.applies_to\\s*\\(\\s*["\']([^"\']+)["\']\\s*,\\s*["\']([^"\']+)["\']\\s*\\)/g)];');
L.push('  for (const m of applies) {');
L.push('    if (TUYA_MFR.test(m[1])) fps.push({ mfr: m[1], productId: m[2], file: filepath, source: "zha" });');
L.push('  }');
L.push('  // P4: standalone Tuya mfr strings');
L.push('  const standalone = [...src.matchAll(/["\'](_TZ[A-Z0-9]{1,5}_[a-zA-Z0-9]+|_TYST1[12]_[a-zA-Z0-9]+|TUYATEC[a-zA-Z0-9_-]+)["\']/g)];');
L.push('  for (const m of standalone) {');
L.push('    if (!fps.find(f => f.mfr === m[1])) fps.push({ mfr: m[1], productId: null, file: filepath, source: "zha" });');
L.push('  }');
L.push('  return fps;');
L.push('}');
L.push('');
L.push('async function listAllPyFiles() {');
L.push('  console.log("[ZHA] Listing ALL quirk directories...");');
L.push('  let topDirs;');
L.push('  try {');
L.push('    topDirs = await fetchJSON(API_BASE + "?ref=dev");');
L.push('  } catch (e) {');
L.push('    console.log("[ZHA] API failed:", e.message);');
L.push('    return [];');
L.push('  }');
L.push('  const dirs = topDirs.filter(f => f.type === "dir");');
L.push('  const pyFiles = [];');
L.push('  // Also get top-level .py files');
L.push('  pyFiles.push(...topDirs.filter(f => f.name.endsWith(".py") && f.name !== "__init__.py"));');
L.push('  console.log("[ZHA] " + dirs.length + " subdirectories to scan...");');
L.push('  for (const dir of dirs) {');
L.push('    try {');
L.push('      const contents = await fetchJSON(dir.url + "?ref=dev");');
L.push('      const pys = contents.filter(f => f.name.endsWith(".py") && f.name !== "__init__.py");');
L.push('      for (const p of pys) { p._dir = dir.name; }');
L.push('      pyFiles.push(...pys);');
L.push('    } catch (e) { /* skip */ }');
L.push('  }');
L.push('  return pyFiles;');
L.push('}');
L.push('');
L.push('async function crawlZHA() {');
L.push('  const pyFiles = await listAllPyFiles();');
L.push('  console.log("[ZHA] " + pyFiles.length + " quirk files to scan");');
L.push('  const allFps = [];');
L.push('  let fetched = 0;');
L.push('  for (let i = 0; i < pyFiles.length; i += 5) {');
L.push('    const batch = pyFiles.slice(i, i + 5);');
L.push('    const results = await Promise.allSettled(batch.map(async f => {');
L.push('      const dirPart = f._dir ? (f._dir + "/") : "";');
L.push('      const url = f.download_url || (RAW_BASE + dirPart + f.name);');
L.push('      const src = await fetch(url);');
L.push('      return parseQuirksFile(src, dirPart + f.name);');
L.push('    }));');
L.push('    for (const r of results) {');
L.push('      if (r.status === "fulfilled") { allFps.push(...r.value); fetched++; }');
L.push('    }');
L.push('    if ((i + 5) % 50 === 0 || i + 5 >= pyFiles.length) {');
L.push('      console.log("[ZHA]   " + Math.min(i+5, pyFiles.length) + "/" + pyFiles.length + " files...");');
L.push('    }');
L.push('  }');
L.push('  // Dedupe');
L.push('  const seen = new Set();');
L.push('  const unique = allFps.filter(fp => {');
L.push('    const k = fp.mfr.toLowerCase();');
L.push('    if (seen.has(k)) return false;');
L.push('    seen.add(k);');
L.push('    return true;');
L.push('  });');
L.push('  fs.mkdirSync(OUT, { recursive: true });');
L.push('  const result = { date: new Date().toISOString(), source: "zha-device-handlers (ALL dirs)", filesFetched: fetched, totalRaw: allFps.length, uniqueFingerprints: unique.length, fingerprints: unique };');
L.push('  fs.writeFileSync(path.join(OUT, "zha.json"), JSON.stringify(result, null, 2));');
L.push('  console.log("[ZHA] " + fetched + " files, " + unique.length + " unique Tuya fingerprints");');
L.push('  return result;');
L.push('}');
L.push('');
L.push('module.exports = crawlZHA;');
L.push('if (require.main === module) crawlZHA().catch(e => { console.error("[ZHA] Error:", e.message); process.exit(1); });');

fs.writeFileSync(target, L.join('\n'));
console.log('Rewritten crawl-zha.js:', L.length, 'lines');
