const fs = require('fs');
const path = require('path');
const target = path.join(__dirname, 'crawl-deconz.js');

const L = [];
L.push('#!/usr/bin/env node');
L.push('/**');
L.push(' * deCONZ Device Database Crawler');
L.push(' * Fetches device definitions from dresden-elektronik/deconz-rest-plugin');
L.push(' * Extracts Tuya fingerprints from JSON device descriptions');
L.push(' * Run: node scripts/sync/crawl-deconz.js');
L.push(' */');
L.push('const { fetch, fetchJSON } = require("./lib/fetch");');
L.push('const fs = require("fs");');
L.push('const path = require("path");');
L.push('');
L.push('const API = "https://api.github.com/repos/dresden-elektronik/deconz-rest-plugin/contents/devices/tuya";');
L.push('const RAW = "https://raw.githubusercontent.com/dresden-elektronik/deconz-rest-plugin/master/devices/";');
L.push('const OUT = path.join(__dirname, "data");');
L.push('');
L.push('const TUYA_MFR = /(_TZ[A-Z0-9]{1,5}_[a-zA-Z0-9]+|_TYST1[12]_[a-zA-Z0-9]+|TUYATEC[a-zA-Z0-9_-]+)/;');
L.push('');
L.push('function parseDeviceFile(src, filename) {');
L.push('  const fps = [];');
L.push('  try {');
L.push('    const json = JSON.parse(src);');
L.push('    // deCONZ JSON format: { "schema":"devcap1.schema.json", "manufacturername":"xxx", "modelid":"yyy", ... }');
L.push('    const mfr = json.manufacturername || null;');
L.push('    const pid = json.modelid || null;');
L.push('    const product = json.product || null;');
L.push('    const vendor = json.vendor || null;');
L.push('    if (mfr && TUYA_MFR.test(mfr)) {');
L.push('      fps.push({ mfr, productId: pid, model: product, description: product, vendor, file: filename, source: "deconz" });');
L.push('    }');
L.push('    // Also check subdevices array');
L.push('    if (json.subdevices) {');
L.push('      for (const sd of json.subdevices) {');
L.push('        const sdMfr = sd.manufacturername || mfr;');
L.push('        const sdPid = sd.modelid || pid;');
L.push('        if (sdMfr && TUYA_MFR.test(sdMfr) && !fps.find(f => f.mfr === sdMfr)) {');
L.push('          fps.push({ mfr: sdMfr, productId: sdPid, model: product, description: product, vendor, file: filename, source: "deconz" });');
L.push('        }');
L.push('      }');
L.push('    }');
L.push('  } catch (e) {');
L.push('    // Not JSON — try regex on raw text');
L.push('    const mfrs = [...src.matchAll(/["\'](_TZ[A-Z0-9]{1,5}_[a-zA-Z0-9]+|_TYST1[12]_[a-zA-Z0-9]+|TUYATEC[a-zA-Z0-9_-]+)["\']/g)];');
L.push('    for (const m of mfrs) {');
L.push('      if (!fps.find(f => f.mfr === m[1])) fps.push({ mfr: m[1], productId: null, file: filename, source: "deconz" });');
L.push('    }');
L.push('  }');
L.push('  return fps;');
L.push('}');
L.push('');
L.push('async function crawlDeCONZ() {');
L.push('  console.log("[DECONZ] Listing device files...");');
L.push('  let files = [];');
L.push('  // Scan tuya/ directory');
L.push('  try {');
L.push('    const tuyaFiles = await fetchJSON(API + "?ref=master");');
L.push('    files.push(...tuyaFiles.filter(f => f.name.endsWith(".json")));');
L.push('    console.log("[DECONZ] Found " + files.length + " Tuya device files");');
L.push('  } catch (e) {');
L.push('    console.log("[DECONZ] Tuya dir:", e.message);');
L.push('  }');
L.push('  // Also check generic dirs that might have Tuya');
L.push('  for (const dir of ["generic", "xiaomi", "ikea"]) {');
L.push('    try {');
L.push('      const dirUrl = API.replace("/tuya", "/" + dir);');
L.push('      const dirFiles = await fetchJSON(dirUrl + "?ref=master");');
L.push('      files.push(...dirFiles.filter(f => f.name.endsWith(".json")));');
L.push('    } catch (e) { /* skip */ }');
L.push('  }');
L.push('');
L.push('  console.log("[DECONZ] " + files.length + " total JSON files to scan");');
L.push('  const allFps = [];');
L.push('  let fetched = 0;');
L.push('  for (const f of files) {');
L.push('    try {');
L.push('      const url = f.download_url || (RAW + "tuya/" + f.name);');
L.push('      const src = await fetch(url);');
L.push('      const fps = parseDeviceFile(src, f.name);');
L.push('      allFps.push(...fps);');
L.push('      fetched++;');
L.push('    } catch (e) { /* skip */ }');
L.push('  }');
L.push('');
L.push('  // Dedupe');
L.push('  const seen = new Set();');
L.push('  const unique = allFps.filter(fp => {');
L.push('    const k = fp.mfr.toLowerCase();');
L.push('    if (seen.has(k)) return false;');
L.push('    seen.add(k);');
L.push('    return true;');
L.push('  });');
L.push('');
L.push('  fs.mkdirSync(OUT, { recursive: true });');
L.push('  const result = { date: new Date().toISOString(), source: "deconz-rest-plugin", filesFetched: fetched, uniqueFingerprints: unique.length, fingerprints: unique };');
L.push('  fs.writeFileSync(path.join(OUT, "deconz.json"), JSON.stringify(result, null, 2));');
L.push('  console.log("[DECONZ] " + fetched + " files, " + unique.length + " unique Tuya fingerprints");');
L.push('  return result;');
L.push('}');
L.push('');
L.push('module.exports = crawlDeCONZ;');
L.push('if (require.main === module) crawlDeCONZ().catch(e => { console.error("[DECONZ] Error:", e.message); process.exit(1); });');

fs.writeFileSync(target, L.join('\n'));
console.log('Written crawl-deconz.js:', L.length, 'lines');
