drivers:
  - changed-files:
      - any-glob-to-any-file: 'drivers/**'

library:
  - changed-files:
      - any-glob-to-any-file: 'lib/**'

workflows:
  - changed-files:
      - any-glob-to-any-file: '.github/workflows/**'

scripts:
  - changed-files:
      - any-glob-to-any-file: '.github/scripts/**'
      - any-glob-to-any-file: 'scripts/**'

documentation:
  - changed-files:
      - any-glob-to-any-file: 'docs/**'
      - any-glob-to-any-file: '*.md'

fingerprints:
  - changed-files:
      - any-glob-to-any-file: 'drivers/*/driver.compose.json'

flow-cards:
  - changed-files:
      - any-glob-to-any-file: 'drivers/*/driver.flow.compose.json'

capabilities:
  - changed-files:
      - any-glob-to-any-file: '.homeycompose/capabilities/**'

locales:
  - changed-files:
      - any-glob-to-any-file: 'locales/**'

config:
  - changed-files:
      - any-glob-to-any-file: 'app.json'
      - any-glob-to-any-file: '.homeycompose/app.json'
      - any-glob-to-any-file: 'package.json'
