#!/usr/bin/env node
'use strict';
/**
 * generate-readme.js (P92.71)
 * Regenerates README.md ENTIRELY from live repo data (app.json, composes,
 * .homeychangelog.json, test suite). Idempotent, deterministic, safe to run
 * in CI (self-improve weekly).
 *
 * Fixes vs previous version:
 *  - `[object Object]` changelog bug (nested 'changelog' key was rendered as a version)
 *  - stale stats (fingerprints/flow cards/classes counted from composes, not app.json)
 *  - missing feature sections (native OTA, smart features, button matrix, WiFi local-first)
 *
 * Usage: node .github/scripts/generate-readme.js
 */
const fs = require('fs');
const path = require('path');
const ROOT = path.join(__dirname, '..', '..');
const DDIR = path.join(ROOT, 'drivers');

const app = JSON.parse(fs.readFileSync(path.join(ROOT, 'app.json'), 'utf8'));
const dirs = fs.readdirSync(DDIR).filter(d => fs.existsSync(path.join(DDIR, d, 'driver.compose.json')));

// ─── Live stats ─────────────────────────────────────────────────────────────
let totalFp = 0;
const fpUnique = new Set();
const pidSet = new Set();
const driverStats = [];
const classes = {};
const capSet = new Set();
let flowTotal = 0;
let fwDrivers = 0;

for (const d of dirs) {
  try {
    const c = JSON.parse(fs.readFileSync(path.join(DDIR, d, 'driver.compose.json'), 'utf8'));
    const fps = (c.zigbee && c.zigbee.manufacturerName) || [];
    totalFp += fps.length;
    for (const m of fps) {fpUnique.add(String(m).toLowerCase());}
    ((c.zigbee && c.zigbee.productId) || []).forEach(p => pidSet.add(p));
    const cl = c.class || 'other';
    classes[cl] = (classes[cl] || 0) + 1;
    (c.capabilities || []).forEach(x => capSet.add(x));
    driverStats.push({ driver: d, fps: fps.length, cls: cl });
    if (c.firmwareUpdates && Array.isArray(c.firmwareUpdates.updates) && c.firmwareUpdates.updates.length) {fwDrivers++;}
  } catch (e) { /* skip */ }
  const ff = path.join(DDIR, d, 'driver.flow.compose.json');
  if (fs.existsSync(ff)) {
    try {
      const f = JSON.parse(fs.readFileSync(ff, 'utf8'));
      flowTotal += (f.triggers || []).length + (f.conditions || []).length + (f.actions || []).length;
    } catch (e) { /* skip */ }
  }
}
// drivers with a driver.firmware.compose.json
for (const d of dirs) {
  if (fs.existsSync(path.join(DDIR, d, 'driver.firmware.compose.json'))) {fwDrivers++;}
}
const composeFlow = path.join(ROOT, '.homeycompose', 'flow');
if (fs.existsSync(composeFlow)) {
  for (const t of ['triggers', 'conditions', 'actions']) {
    const dd = path.join(composeFlow, t);
    if (fs.existsSync(dd)) {flowTotal += fs.readdirSync(dd).filter(f => f.endsWith('.json')).length;}
  }
}
driverStats.sort((a, b) => b.fps - a.fps);
const zigbeeCount = dirs.filter(d => !d.startsWith('wifi_')).length;
const wifiCount = dirs.filter(d => d.startsWith('wifi_')).length;

// Test count (from the last suite — count test files as a stable proxy)
let testFiles = 0;
const testDir = path.join(ROOT, 'test');
if (fs.existsSync(testDir)) {
  const countTests = (dir) => {
    for (const f of fs.readdirSync(dir)) {
      const fp = path.join(dir, f);
      if (fs.statSync(fp).isDirectory()) {countTests(fp);}
      else if (f.endsWith('.test.js')) {testFiles++;}
    }
  };
  countTests(testDir);
}

// ─── Changelog (BOTH formats, 'changelog' key excluded) ─────────────────────
let cl = {};
try {cl = JSON.parse(fs.readFileSync(path.join(ROOT, '.homeychangelog.json'), 'utf8'));} catch (e) { /* skip */ }
const clEntries = Object.keys(cl)
  .filter(k => k !== 'changelog' && /^\d+\.\d+\.\d+$/.test(k))
  .sort((a, b) => b.localeCompare(a, undefined, { numeric: true }))
  .slice(0, 12)
  .map(v => {
    const e = cl[v];
    const txt = typeof e === 'string' ? e : (e && (e.en || e.summary)) || '';
    const flat = String(txt).replace(/\|/g, '\\|').replace(/\n/g, ' ');
    return `| **v${v}** | ${flat.length > 140 ? flat.slice(0, 137) + '…' : flat} |`;
  })
  .join('\n');

// ─── SVG icons ──────────────────────────────────────────────────────────────
let svgCount = 0;
const countSvg = (dir) => {
  if (!fs.existsSync(dir)) {return;}
  for (const f of fs.readdirSync(dir)) {
    const fp = path.join(dir, f);
    if (fs.statSync(fp).isDirectory()) {countSvg(fp);}
    else if (f.endsWith('.svg')) {svgCount++;}
  }
};
countSvg(path.join(ROOT, 'assets'));
for (const d of dirs) {countSvg(path.join(DDIR, d, 'assets'));}

const fmt = n => n.toLocaleString('en-US');
const date = new Date().toISOString().split('T')[0];
const version = app.version;

const top20 = driverStats.slice(0, 20)
  .map((s, i) => `| ${i + 1} | \`${s.driver}\` | ${fmt(s.fps)} |`).join('\n');
const classRows = Object.entries(classes).sort((a, b) => b[1] - a[1])
  .map(([k, v]) => `| ${k} | ${v} |`).join('\n');

// ─── README ─────────────────────────────────────────────────────────────────
const readme = `# Tuya Unified Zigbee App for Homey

<!-- AUTO-GENERATED by .github/scripts/generate-readme.js — do not edit manually (weekly self-improve) -->

[![Version](https://img.shields.io/badge/dynamic/json?url=https%3A%2F%2Fraw.githubusercontent.com%2Fdlnraja%2Fcom.tuya.zigbee%2Fmaster%2Fapp.json&query=%24.version&label=version&color=blue)](https://homey.app/a/com.dlnraja.tuya.zigbee/)
[![Drivers](https://img.shields.io/badge/drivers-${dirs.length}-brightgreen)](https://homey.app/a/com.dlnraja.tuya.zigbee/)
[![Fingerprints](https://img.shields.io/badge/fingerprints-${fmt(fpUnique.size)}%20unique-green)](https://homey.app/a/com.dlnraja.tuya.zigbee/)
[![Flow Cards](https://img.shields.io/badge/flow%20cards-${fmt(flowTotal)}-blue)](https://homey.app/a/com.dlnraja.tuya.zigbee/)
[![Native OTA](https://img.shields.io/badge/native%20OTA-${fwDrivers}%20drivers-orange)](docs/P92_70_HOMEY_2026_OTA_NATIVE.md)
[![SDK](https://img.shields.io/badge/SDK-3-orange)](https://apps.developer.homey.app/)
[![License](https://img.shields.io/badge/license-MIT-green)](LICENSE)

A community-driven Homey app that brings **local control** to Tuya Zigbee devices — no cloud, no internet needed. Covers switches, sensors, lights, thermostats, covers, locks and more across **${dirs.length} drivers** and **${fmt(fpUnique.size)} unique device fingerprints** (${fmt(totalFp)} including case variants for bulletproof pairing).

**Key features:**
- **Local-only** — everything runs on your Homey, nothing goes to the cloud
- **Native Zigbee OTA** — firmware updates shipped in-app for ${fwDrivers} drivers (Homey v13.2.0+), SHA512-verified
- **Hybrid protocol engine** — auto-detects Tuya DP (0xEF00) vs standard ZCL per device
- **Bulletproof pairing** — every fingerprint exists in 4 case combinations; runtime matching is fully case-insensitive
- **Smart battery** — non-linear per-chemistry curves, collapse-aware smoothing, no fabricated values
- **${fmt(flowTotal)} flow cards** — triggers, conditions & actions in EN, FR, NL, DE
- **Hue-style smart features** — motion lighting with quiet hours, circadian (real solar position), wake-up/sleep ramps, scene capture/cycle

---

## Installation

| Method | Link |
|--------|------|
| **Homey App Store** | [Install from Homey App Store](https://homey.app/a/com.tuya.zigbee/) |
| **Test Version** | [Install Test Version](https://homey.app/a/com.dlnraja.tuya.zigbee/test/) |
| **GitHub Releases** | [View Releases](https://github.com/dlnraja/com.tuya.zigbee/releases) |

---

## Statistics

| Metric | Value |
|--------|-------|
| **App Version** | v${version} |
| **Drivers** | ${dirs.length} (${zigbeeCount} Zigbee + ${wifiCount} WiFi) |
| **Unique Fingerprints** | ${fmt(fpUnique.size)} |
| **Pairing Variants** | ${fmt(totalFp)} (4 case combos per fingerprint) |
| **Unique Product IDs** | ${fmt(pidSet.size)} |
| **Flow Cards** | ${fmt(flowTotal)} |
| **Unique Capabilities** | ${capSet.size} |
| **Native OTA Drivers** | ${fwDrivers} |
| **Test Suites** | ${testFiles} files |
| **SVG Icons** | ${fmt(svgCount)} |
| **Languages** | EN, FR, NL, DE |
| **SDK / Homey** | 3 / >= 12.2.0 |
| **Last Updated** | ${date} |

### Top 20 Drivers by Fingerprint Count

| # | Driver | Fingerprints |
|---|--------|-------------|
${top20}

### Drivers by Device Class

| Class | Count |
|-------|-------|
${classRows}

---

## Latest Updates

<!-- CHANGELOG_START - Auto-updated from .homeychangelog.json -->

| Version | Changes |
|---------|---------|
${clEntries}

<!-- CHANGELOG_END -->

---

## Key Features

### Native Zigbee OTA (Homey v13.2.0+)
- Firmware updates shipped **in-app** for ${fwDrivers} drivers — flash directly from Homey, no manufacturer app needed
- OEM images only (Koenkk zigbee-OTA), **SHA512-verified at build, sha256-verified at install**
- Weekly auto-refresh via CI — new images land automatically when available
- For TS0601 MCU devices (no public firmware exists): detect + notify + guidance

### Dual Protocol Support
- **Tuya DP Protocol** (Cluster 0xEF00) — full datapoint engine with a 756-manufacturer DP registry
- **Standard ZCL** — for native Zigbee 3.0 devices
- **Auto-Detection** — observes the device, then picks the best protocol with cross-protocol fallback

### Bulletproof Pairing & Recognition
- Every Tuya fingerprint in **4 case combinations** (pairing is case-sensitive in Homey core)
- Runtime matching via a single NFKD caseless normalizer (LRU-cached)
- Curated per-device routing database (mfs_db) with Sacred-Couple mfr+pid discipline

### Buttons (physical + virtual)
- 10 detection methods with layered dedup (TSN ring, per-gang debounce, virtual/physical windows)
- One dropdown **matrix card**: button × action (single/double/long/triple/release)
- Scene mode auto-switch (0x8004) with manual-toggle detection
- Anti-spam: throttled virtual toggles, TX rate limiting on sleepy devices

### Smart Battery Management
- 15+ battery chemistries with non-linear discharge curves
- Collapse-aware smoothing (real cell death surfaces immediately)
- Last-known persistence for sleepy devices; estimates marked, never fabricated
- Cycle counting and health intelligence

### Hue-Style Smart Features
- Motion lighting with quiet-hours window + lux guard + auto-off
- Circadian lighting driven by **real solar elevation**
- Wake-up / sleep ramps, scene capture/apply/cycle (5 slots), all-off

### WiFi Devices (Tuya Local-First)
- Local LAN control (protocols 3.1–3.5) with optional cloud recovery of local keys
- SmartLife QR pairing — no developer account needed
- UDP discovery with IP self-healing

---

## Documentation

| Doc | Content |
|-----|---------|
| [docs/INDEX.md](docs/INDEX.md) | Full documentation index |
| [docs/P92_64_BUTTON_CROSS_MATRIX.md](docs/P92_64_BUTTON_CROSS_MATRIX.md) | Button implementations cross-reference (all sources, dated) |
| [docs/P92_70_HOMEY_2026_OTA_NATIVE.md](docs/P92_70_HOMEY_2026_OTA_NATIVE.md) | Native OTA + Homey 2026 ecosystem |
| [docs/CONTRIBUTING_DEV.md](docs/CONTRIBUTING_DEV.md) | Developer workflow (master/stable, tools, CI) |
| [AGENTS.md](AGENTS.md) | Project rules for AI agents |
| [CHANGELOG.md](CHANGELOG.md) | Full changelog |

## Community & Support

- **Issues**: [GitHub Issues](https://github.com/dlnraja/com.tuya.zigbee/issues)
- **Forum**: [Homey Community Topic](https://community.homey.app/t/app-pro-universal-tuya-zigbee-device-app-test/140352)
- **Upstream**: Fork of [JohanBendz/com.tuya.zigbee](https://github.com/JohanBendz/com.tuya.zigbee) (superset: ${dirs.length} vs 113 drivers)

## License

MIT — see [LICENSE](LICENSE) and [NOTICE](NOTICE). Factual data (fingerprints, datapoints, clusters) cross-referenced from zigbee2mqtt, ZHA, Hubitat, deCONZ and the Homey community — implementations are our own.
`;

fs.writeFileSync(path.join(ROOT, 'README.md'), readme);
console.log(`[generate-readme] README.md regenerated — v${version}, ${dirs.length} drivers, ${fmt(fpUnique.size)} unique FPs, ${fmt(flowTotal)} flow cards, ${fwDrivers} OTA drivers, ${testFiles} test files`);
