/**
 * Project Rules - Condensed context for AI automation
 * Sources: CRITICAL_MISTAKES.md, DEVELOPMENT_RULES.md, UNSUPPORTED_DEVICES.md, Windsurf workflows, memory rules
 */
const PROJECT_RULES = [
'## Universal Tuya Zigbee - Project Rules for AI',
'',
'### IDENTITY',
'- App: com.dlnraja.tuya.zigbee | SDK3 | Repo: dlnraja/com.tuya.zigbee',
'- Forum: topics 140352 (dlnraja), 26439 (JohanBendz)',
'',
'### FINGERPRINT RULES (CRITICAL)',
'- Fingerprint = manufacturerName + productId COMBINED',
'- Same mfr in multiple drivers is NORMAL if productId differs',
'- TRUE collision = same mfr + same pid in incompatible drivers',
'- No wildcards in SDK3 (_TZE284_* is INVALID)',
'- Case-insensitive: include both _TZE200_ and _tze200_',
'- TS0601 collisions are inherent to Tuya architecture',
'',
'### CODE RULES',
'- Settings keys: zb_model_id NOT zb_modelId, zb_manufacturer_name NOT zb_manufacturerName',
'- Flow triggers: NO titleFormatted with [[device]] - use title field',
'- Import: require(../../lib/tuya/TuyaZigbeeDevice) NOT require(../../lib/TuyaZigbeeDevice)',
'- Mixin order: PhysicalButtonMixin(VirtualButtonMixin(HybridSwitchBase))',
'- Flow IDs: {driver}_physical_gang{N}_{on|off}',
'- Backlight values: off, normal, inverted (strings not numbers)',
'- Press type 0-indexed: 0=single 1=double 2=hold',
'',
'### TUYA DP PROTOCOL',
'- Cluster 0xEF00 (61184)',
'- Types: 0=Raw 1=Bool 2=Value 3=String 4=Enum 5=Bitmap',
'- DP1-8: gang states | DP14: power-on | DP15: backlight | DP101: child_lock',
'- Values may need division: temp/10, hum/10, battery/2',
'- Double-division bug: skip auto-convert when dpMappings divisor !== 1',
'',
'### BATTERY AND MAINS',
'- Sleepy devices: first report up to 24h - NOT a bug',
'- mainsPowered devices must NOT have measure_battery',
'- batteryPercentageRemaining===0 is VALID (dead battery)',
'- Store-based restore: persist on every update, restore on init',
'',
'### BSEED ZCL-ONLY',
'- FPs: _TZ3000_l9brjwau, _TZ3000_blhvsaqf, _TZ3000_ysdv91bk, _TZ3000_hafsqare, _TZ3000_e98krvvk, _TZ3000_iedbgyxt',
'- Group toggle bug: firmware broadcasts ZCL to ALL EPs',
'- Fix: _removeGroupMemberships + _lastCommandedGang + broadcast filter 2s',
'',
'### UNSUPPORTED DEVICES',
'- Solar inverters (APsystems, Enphase, SolarEdge) = proprietary protocol',
'- Red flags: requires manufacturer gateway, no _TZ* prefix',
'- For solar monitoring: use bidirectional energy meters (_TZE204_ac0fhfiq)',
'',
'### RESPONSE GUIDELINES',
'- If fingerprint supported: tell which driver, how to pair, link to install',
'- If not supported: ask for device interview from tools.developer.homey.app/tools/zigbee',
'- If interview data: analyze clusters, endpoints, suggest driver',
'- Cross-reference Z2M, ZHA, Blakadder when possible',
'- NEVER publish locally - use GitHub Actions',
'- Install test: https://homey.app/a/com.dlnraja.tuya.zigbee/test/',
'- Issues: https://github.com/dlnraja/com.tuya.zigbee/issues',
].join('\n');

module.exports = { PROJECT_RULES };