#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path');
const{fetchWithRetry}=require('./retry-helper');
const{getForumAuth,refreshCsrf,fmtCk,FORUM}=require('./forum-auth');
const PID=645318,ROOT=process.cwd(),TPL=path.join(__dirname,'..','templates','forum-post-1.md');
function stats(){const D=path.join(ROOT,'drivers');let dc=0,fp=0,fc=0;try{const ds=fs.readdirSync(D).filter(d=>fs.existsSync(path.join(D,d,'driver.compose.json')));dc=ds.length;for(const d of ds){try{const c=JSON.parse(fs.readFileSync(path.join(D,d,'driver.compose.json'),'utf8'));if(Array.isArray(c.zigbee)){for(const z of c.zigbee){if(Array.isArray(z.manufacturerName))fp+=z.manufacturerName.length}}else if(c.zigbee&&Array.isArray(c.zigbee.manufacturerName)){fp+=c.zigbee.manufacturerName.length}}catch{}try{const f=path.join(D,d,'driver.flow.compose.json');if(fs.existsSync(f)){const j=JSON.parse(fs.readFileSync(f,'utf8'));fc+=(j.triggers||[]).length+(j.conditions||[]).length+(j.actions||[]).length}}catch{}}}catch{}return{dc,fp,fc}}
function cl(){try{const c=JSON.parse(fs.readFileSync(path.join(ROOT,'.homeychangelog.json'),'utf8'));const k=Object.keys(c).sort((a,b)=>b.localeCompare(a,undefined,{numeric:true}));const l=c[k[0]]?.en||'Improvements.';const p=[];for(let i=1;i<Math.min(k.length,8);i++)if(c[k[i]]?.en)p.push('**v'+k[i]+'**: '+c[k[i]].en);return{l,p:p.join('\n\n')}}catch{return{l:'Improvements.',p:''}}}
function build(){let t=fs.readFileSync(TPL,'utf8');const v=require(path.join(ROOT,'app.json')).version;const s=stats(),c=cl(),d=new Date().toISOString().slice(0,10);t=t.replace(/\{\{VERSION}}/g,v).replace(/\{\{DRIVERS}}/g,s.dc).replace(/\{\{FINGERPRINTS}}/g,s.fp.toLocaleString('en-US')).replace(/\{\{FLOW_CARDS}}/g,s.fc.toLocaleString('en-US')).replace(/\{\{DATE}}/g,d).replace(/\{\{CHANGELOG_LATEST}}/g,c.l).replace(/\{\{CHANGELOG_PREVIOUS}}/g,c.p);return t}
async function main(){const raw=build();console.log('Content:',raw.length,'ch');const auth=await getForumAuth();if(!auth){console.error('No auth');process.exit(1)}if(auth.type==='session')await refreshCsrf(auth);const h=auth.type==='apikey'?{'User-Api-Key':auth.key}:{'X-CSRF-Token':auth.csrf,'X-Requested-With':'XMLHttpRequest',Cookie:fmtCk(auth.cookies)};h['Content-Type']='application/json';const r=await fetchWithRetry(FORUM+'/posts/'+PID,{method:'PUT',headers:h,body:JSON.stringify({post:{raw}})},{retries:3,label:'editPost1'});if(!r.ok){const d=await r.json().catch(()=>({}));throw new Error('Edit failed:'+r.status+' '+JSON.stringify(d).slice(0,200))}console.log('Post #1 updated OK')}
main().catch(e=>{console.error('Fatal:',e.message);process.exit(1)});
