#!/usr/bin/env node
'use strict';

/**
 * INDEX - Scripts monitoring
 * Auto-generated by UltimateProjectOrganizer
 */

const FINAL_COHERENCE_CHECK = require('./FINAL_COHERENCE_CHECK.js');
const HEALTH_CHECK = require('./HEALTH_CHECK.js');
const monitor_and_fix = require('./monitor_and_fix.js');
const PRE_COMMIT_CHECKS = require('./PRE_COMMIT_CHECKS.js');

module.exports = {
  FINAL_COHERENCE_CHECK,
  HEALTH_CHECK,
  monitor_and_fix,
  PRE_COMMIT_CHECKS
};
