#!/usr/bin/env node
'use strict';

/**
 * INDEX - Scripts organisation
 * Auto-generated by UltimateProjectOrganizer
 */

const CLEAN_APP_JSON = require('./CLEAN_APP_JSON.js');
const FINAL_CLEANUP_AND_PUBLISH = require('./FINAL_CLEANUP_AND_PUBLISH.js');
const ORGANIZE_PROJECT = require('./ORGANIZE_PROJECT.js');
const ORGANIZE_PROJECT_CLEAN = require('./ORGANIZE_PROJECT_CLEAN.js');
const ORGANIZE_PROJECT_FILES = require('./ORGANIZE_PROJECT_FILES.js');

module.exports = {
  CLEAN_APP_JSON,
  FINAL_CLEANUP_AND_PUBLISH,
  ORGANIZE_PROJECT,
  ORGANIZE_PROJECT_CLEAN,
  ORGANIZE_PROJECT_FILES
};
