// Auto-generated by tools/ci/generate-flow-handlers.js — review before commit.
'use strict';

const { Driver } = require('homey');

class SmartDoorWindowSensorDriver extends Driver {

  async onInit() {
    await super.onInit();
    if (this._flowCardsRegistered) {return;}
    this._flowCardsRegistered = true;

      // === AUTO-GENERATED FLOW HANDLERS ===
      // Generated by tools/ci/generate-flow-handlers.js
      // Edit if you need custom behaviour.

      this.homey.flow.getConditionCard('smart_door_window_sensor_alarm_contact_active')?.registerRunListener(async (args) => {
        if (!args.device) {return false;}
        return args.device.getCapabilityValue('alarm_contact') === true;
      });
  }
}

module.exports = SmartDoorWindowSensorDriver;
