'use strict';

const { ZigBeeDevice } = require('homey-zigbeedriver');
const { CLUSTER } = require('zigbee-clusters');
const TuyaClusterHandler = require('../../utils/tuya-cluster-handler');

class GarageDoorControllerAcDevice extends ZigBeeDevice {

  async onNodeInit({ zclNode }) {
    this.log('garage_door_controller_ac initialized');

    // Call parent
    await super.onNodeInit({ zclNode });

    // Auto-detect device type and initialize Tuya cluster handler
    const deviceType = TuyaClusterHandler.detectDeviceType('garage_door_controller_ac');
    const tuyaInitialized = await TuyaClusterHandler.init(this, zclNode, deviceType);
    
    if (tuyaInitialized) {
      this.log('✅ Tuya cluster handler initialized for type:', deviceType);
    } else {
      this.log('⚠️  No Tuya cluster found, using standard Zigbee');
      
      // Fallback to standard cluster handling if needed
      await this.registerStandardCapabilities();
    }

    // Mark device as available
    await this.setAvailable();
  }

  /**
   * Register standard Zigbee capabilities (fallback)
   */
  async registerStandardCapabilities() {
    // Battery
    if (this.hasCapability('measure_battery')) {
      try {
        this.registerCapability('measure_battery', CLUSTER.POWER_CONFIGURATION, {
          get: 'batteryPercentageRemaining',
          report: 'batteryPercentageRemaining',
          reportParser: value => { this.log('Battery raw value:', value); // Smart calculation: check if value is already 0-100 or 0-200 if (value <= 100) { return Math.max(0, Math.min(100, value)); } else { return Math.max(0, Math.min(100, value / 2)); } },
          getParser: value => Math.max(0, Math.min(100, value / 2))
        });
      } catch (err) {
        this.log('Could not register battery capability:', err.message);
      }
    }
  }

  async onDeleted() {
    this.log('garage_door_controller_ac deleted');
  }
  // ========================================
  // FLOW METHODS - Auto-generated
  // ========================================

  /**
   * Trigger flow with context data
   */
  async triggerFlowCard(cardId, tokens = {}) {
    try {
      const flowCard = this.homey.flow.getDeviceTriggerCard(cardId);
      await flowCard.trigger(this, tokens);
      this.log(`✅ Flow triggered: ${cardId}`, tokens);
    } catch (err) {
      this.error(`❌ Flow trigger error: ${cardId}`, err);
    }
  }

  /**
   * Check if any alarm is active
   */
  async checkAnyAlarm() {
    const capabilities = this.getCapabilities();
    for (const cap of capabilities) {
      if (cap.startsWith('alarm_')) {
        const value = this.getCapabilityValue(cap);
        if (value === true) return true;
      }
    }
    return false;
  }

  /**
   * Get current context data
   */
  getContextData() {
    const context = {
      time_of_day: this.getTimeOfDay(),
      timestamp: new Date().toISOString()
    };
    
    // Add available sensor values
    const caps = this.getCapabilities();
    if (caps.includes('measure_luminance')) {
      context.luminance = this.getCapabilityValue('measure_luminance') || 0;
    }
    if (caps.includes('measure_temperature')) {
      context.temperature = this.getCapabilityValue('measure_temperature') || 0;
    }
    if (caps.includes('measure_humidity')) {
      context.humidity = this.getCapabilityValue('measure_humidity') || 0;
    }
    if (caps.includes('measure_battery')) {
      context.battery = this.getCapabilityValue('measure_battery') || 0;
    }
    
    return context;
  }

  /**
   * Get time of day
   */
  getTimeOfDay() {
    const hour = new Date().getHours();
    if (hour >= 5 && hour < 12) return 'morning';
    if (hour >= 12 && hour < 17) return 'afternoon';
    if (hour >= 17 && hour < 22) return 'evening';
    return 'night';
  }




  /**
   * INTELLIGENT BATTERY MONITORING
   * Auto-generated by IntelligentBatteryManager
   */
  
  async monitorBattery() {
    try {
      const batteryLevel = this.getCapabilityValue('measure_battery');
      
      if (batteryLevel !== null && batteryLevel !== undefined) {
        // Battery level categorization
        if (batteryLevel <= 10) {
          this.setWarning('⚠️ CRITICAL: Battery ' + batteryLevel + '% - Replace immediately!');
          this.log('Battery CRITICAL:', batteryLevel + '%');
        } else if (batteryLevel <= 20) {
          this.setWarning('Battery low: ' + batteryLevel + '% - Replace soon');
          this.log('Battery LOW:', batteryLevel + '%');
        } else if (batteryLevel <= 30) {
          this.log('Battery WARNING level:', batteryLevel + '%');
        } else {
          this.unsetWarning();
        }
        
        // Battery type info
        const supportedBatteries = ["CR2032","AAA"];
        this.log('Supported batteries:', supportedBatteries.join(', '));
        
        // Estimate remaining time
        if (batteryLevel <= 20) {
          const estimatedDays = Math.floor((batteryLevel / 20) * 30);
          this.log('Estimated remaining: ~' + estimatedDays + ' days');
        }
      }
    } catch (err) {
      this.error('Battery monitoring error:', err);
    }
  }
  
  /**
   * Battery change detection
   */
  async detectBatteryChange(oldValue, newValue) {
    try {
      // Detect battery replacement (jump from low to high)
      if (oldValue < 30 && newValue > 80) {
        this.log('🔋 Battery replaced detected!');
        if (this.homey && this.homey.flow) {
          this.homey.flow.getDeviceTriggerCard('device_battery_changed')
            .trigger(this, { old_battery: oldValue, new_battery: newValue })
            .catch(err => this.error('Flow trigger error:', err));
        }
        
        // Reset warnings
        this.unsetWarning();
      }
    } catch (err) {
      this.error('Battery change detection error:', err);
    }
  }

}

module.exports = GarageDoorControllerAcDevice;
