defaults:
  official_manufacturer: 0.92
  official_platform: 0.88
  zigbee_cert_listing: 0.86
  upstream_repo: 0.85
  z2m_converters_repo: 0.82
  zha_quirks_repo: 0.80
  deconz_supported_page: 0.78
  community_database: 0.80
  tasmota_zigbee_docs: 0.70
  iobroker_zigbee_repo: 0.70
  reputable_forum: 0.75
  product_manual_pdf: 0.70
  large_retailer: 0.55
  tech_blog: 0.55
  video_demo: 0.52
  small_shop: 0.40
  unknown_site: 0.25
  local_pairing_log: 0.90
  local_event_log: 0.88
  local_sniffer_dump: 0.93

bonuses:
  multi_source_agreement: +0.10
  dp_log_evidence: +0.15
  xdevice_analogy: +0.05

penalties:
  mf_mismatch: -0.15
  contradiction: -0.20
  single_source_only: -0.10

thresholds:
  propose_threshold: 0.60
  confirm_threshold: 0.85
  quarantine_threshold: 0.45
