// Auto-generated by tools/ci/generate-flow-handlers.js — review before commit.
'use strict';

const { Driver } = require('homey');

class PetFeederZigbeeDriver extends Driver {

  async onInit() {
    await super.onInit();
    if (this._flowCardsRegistered) return;
    this._flowCardsRegistered = true;

      // === AUTO-GENERATED FLOW HANDLERS ===
      // Generated by tools/ci/generate-flow-handlers.js
      // Edit if you need custom behaviour.

      this.homey.flow.getActionCard('pet_feeder_zigbee_feed')?.registerRunListener(async (args) => {
        if (!args.device) return false;
        return true; // TODO: implement action for pet_feeder_zigbee_feed
      });
  }
}

module.exports = PetFeederZigbeeDriver;
