// Auto-generated by tools/ci/generate-flow-handlers.js — review before commit.
'use strict';

const { Driver } = require('homey');

class LightSensorOutdoorDriver extends Driver {

  async onInit() {
    await super.onInit();
    if (this._flowCardsRegistered) return;
    this._flowCardsRegistered = true;

      // === AUTO-GENERATED FLOW HANDLERS ===
      // Generated by tools/ci/generate-flow-handlers.js
      // Edit if you need custom behaviour.

      this.homey.flow.getConditionCard('light_sensor_outdoor_battery_low')?.registerRunListener(async (args) => {
        if (!args.device) return false;
        return args.device.getCapabilityValue('light_sensor_outdoor_battery') === true;
      });
  }
}

module.exports = LightSensorOutdoorDriver;
