'use strict';

/**
 * DeadFlowAutoWire: give dead driver triggers and listener-less conditions a
 * capability-based behaviour (P2803).
 *
 * The map lives in config/flow/dead-flow-autowire.json and is generated by
 * tools/flow/build-dead-flow-autowire.js from each card's English title,
 * argument and the driver's capabilities. Only unambiguous cards are listed.
 *
 * Safety:
 * - triggers fire only for the device's own driver, only when the mapped
 *   capability changes, and the card must be declared in the manifest;
 * - conditions return false (never throw) when the capability is missing or
 *   has no value. A driver that later registers its own listener replaces ours;
 * - the map is loaded lazily once, then indexed (memory bounded by the JSON size).
 */

let _map = null;
let _trigIndex = null;

function loadMap() {
  if (_map) {return _map;}
  try {
    _map = require('../../config/flow/dead-flow-autowire.json');
  } catch (_) {
    _map = { triggers: {}, conditions: {} };
  }
  return _map;
}

function triggerIndex() {
  if (_trigIndex) {return _trigIndex;}
  _trigIndex = new Map();
  for (const [id, v] of Object.entries(loadMap().triggers || {})) {
    const k = `${v.driver}|${v.cap}`;
    if (!_trigIndex.has(k)) {_trigIndex.set(k, []);}
    _trigIndex.get(k).push({ id, when: v.when });
  }
  return _trigIndex;
}

/** Trigger ids mapped for this driver/capability whose `when` matches value. */
function mappedTriggerIds(driverId, capability, value) {
  const list = triggerIndex().get(`${driverId}|${capability}`);
  if (!list) {return [];}
  const out = [];
  for (const { id, when } of list) {
    if (when === 'change' || when === Boolean(value)) {out.push(id);}
  }
  return out.slice(0, 6);
}

function _num(v) {
  const n = Number(v);
  return Number.isFinite(n) ? n : null;
}

/** Evaluate a mapped condition against a device. Never throws. */
function evaluateCondition(def, device, args) {
  try {
    if (!def || !device || typeof device.getCapabilityValue !== 'function') {return false;}
    if (typeof device.hasCapability === 'function' && !device.hasCapability(def.cap)) {return false;}
    const v = device.getCapabilityValue(def.cap);
    if (v === null || v === undefined) {return false;}
    if (def.op === true) {return v === true;}
    const cur = _num(v);
    const thr = _num(args && args[def.arg]);
    if (cur === null || thr === null) {return false;}
    return def.op === 'above' ? cur > thr : cur < thr;
  } catch (_) {
    return false;
  }
}

/** Register run listeners for mapped conditions declared in this build. */
function registerDeadConditions(homey, { log } = {}) {
  const flow = homey && homey.flow;
  if (!flow || typeof flow.getConditionCard !== 'function') {return 0;}
  let n = 0;
  for (const [id, def] of Object.entries(loadMap().conditions || {})) {
    try {
      const card = flow.getConditionCard(id);
      if (!card || typeof card.registerRunListener !== 'function') {continue;}
      card.registerRunListener(async (args) => evaluateCondition(def, args && args.device, args));
      n++;
    } catch (_) { /* not declared in this build */ }
  }
  if (log && n) {log(`P2803 dead conditions wired: ${n}`);}
  return n;
}

function _tokensFor(homey, id, value) {
  const tokens = {};
  let def = null;
  try {
    const list = homey && homey.manifest && homey.manifest.flow && homey.manifest.flow.triggers;
    def = Array.isArray(list) ? list.find((t) => t && t.id === id) : null;
  } catch (_) { def = null; }
  for (const t of (def && def.tokens) || []) {
    if (!t || !t.name) {continue;}
    if (t.type === 'number') {tokens[t.name] = Number.isFinite(Number(value)) ? Number(value) : 0;} else if (t.type === 'boolean') {tokens[t.name] = Boolean(value);} else {tokens[t.name] = String(value);}
  }
  return tokens;
}

/**
 * Fire mapped dead triggers for a device (for trees without CapabilityChangedFlowEmitter).
 * Uses the device's own triggerFlowCard when present (declared-id check, suppression).
 * @returns {Promise<number>} cards fired
 */
async function fireMappedTriggers(device, capability, value) {
  let fired = 0;
  try {
    const driverId = device && device.driver && device.driver.id;
    if (!driverId) {return 0;}
    for (const id of mappedTriggerIds(String(driverId), capability, value)) {
      const tokens = _tokensFor(device.homey, id, value);
      try {
        if (typeof device.triggerFlowCard === 'function') {
          // eslint-disable-next-line no-await-in-loop
          if (await device.triggerFlowCard(id, tokens, { capability, value }) !== false) {fired++;}
        } else {
          const card = device.homey.flow.getDeviceTriggerCard(id);
          // eslint-disable-next-line no-await-in-loop
          await card.trigger(device, tokens, { capability, value });
          fired++;
        }
      } catch (_) { /* card not declared / not usable: stay silent */ }
    }
  } catch (_) { /* soft */ }
  return fired;
}

function _resetForTests() { _map = null; _trigIndex = null; }

module.exports = { mappedTriggerIds, fireMappedTriggers, evaluateCondition, registerDeadConditions, loadMap, _resetForTests };
