'use strict';

const { ZigBeeDriver } = require('homey-zigbeedriver');

class UsbOutlet2portDriver extends ZigBeeDriver {

  async onInit() {
    this.log('UsbOutlet2portDriver initialized');
    
    // Flow cards are auto-generated by homey app build
    // No manual registration needed
  }
}

module.exports = UsbOutlet2portDriver;
