'use strict';

const { ZigBeeDriver } = require('homey-zigbeedriver');

const RootDevice = require('./device.js');
const Port2Device = require('./port2.device.js');

class UsbOutlet2PortDriver extends ZigBeeDriver {

  async onInit() {
    this.log('UsbOutlet2PortDriver initialized with sub device support');
    
    // Flow cards are auto-generated by homey app build
    // No manual registration needed
  }

  /**
   * Map device class based on subDeviceId
   * Root device (Port 1) uses RootDevice with all capabilities
   * Sub device (Port 2) uses Port2Device with only onoff
   */
  onMapDeviceClass(device) {
    const { subDeviceId } = device.getData();
    
    if (subDeviceId === 'port2') {
      this.log('[DRIVER] Mapping to Port2Device (sub device)');
      return Port2Device;
    }
    
    this.log('[DRIVER] Mapping to RootDevice (main device)');
    return RootDevice;
  }

}

module.exports = UsbOutlet2PortDriver;
