'use strict';

const { ZigBeeDriver } = require('homey-zigbeedriver');

class ButtonWireless6Driver extends ZigBeeDriver {

  async onInit() {
    this.log('ButtonWireless6Driver initialized');
    
    // Flow cards are auto-generated by homey app build
    // No manual registration needed
  }
}

module.exports = ButtonWireless6Driver;
