#!/usr/bin/env node
'use strict';

/**
 * INDEX - Scripts d'automation
 * Auto-generated by ORGANIZE_ALL_JS_FILES
 */

const AUTO_DIAGNOSTIC_SYSTEM = require('./AUTO_DIAGNOSTIC_SYSTEM.js');
const AUTO_GEN_2025 = require('./AUTO_GEN_2025.js');
const AUTO_ORGANIZE_DOCS = require('./AUTO_ORGANIZE_DOCS.js');
const AUTO_ORGANIZE_REPORTS = require('./AUTO_ORGANIZE_REPORTS.js');
const AUTO_SYNC_DRIVERS_TO_APP_JSON = require('./AUTO_SYNC_DRIVERS_TO_APP_JSON.js');
const FULL_AUTOMATION_WORKFLOW = require('./FULL_AUTOMATION_WORKFLOW.js');
const HOMEY_DASHBOARD_AUTOMATION = require('./HOMEY_DASHBOARD_AUTOMATION.js');
const MASSIVE_POWER_RENAME = require('./MASSIVE_POWER_RENAME.js');
const MASTER_AUTO_FIX = require('./MASTER_AUTO_FIX.js');
const SAFE_PUSH_AND_PUBLISH = require('./SAFE_PUSH_AND_PUBLISH.js');
const monitor_and_fix = require('./monitor_and_fix.js');
const publish_and_promote = require('./publish_and_promote.js');
const tuya-cluster-handler = require('./tuya-cluster-handler.js');

module.exports = {
  AUTO_DIAGNOSTIC_SYSTEM,
  AUTO_GEN_2025,
  AUTO_ORGANIZE_DOCS,
  AUTO_ORGANIZE_REPORTS,
  AUTO_SYNC_DRIVERS_TO_APP_JSON,
  FULL_AUTOMATION_WORKFLOW,
  HOMEY_DASHBOARD_AUTOMATION,
  MASSIVE_POWER_RENAME,
  MASTER_AUTO_FIX,
  SAFE_PUSH_AND_PUBLISH,
  monitor_and_fix,
  publish_and_promote,
  tuya-cluster-handler
};
