// Auto-generated by tools/ci/generate-flow-handlers.js — review before commit.
'use strict';

const { Driver } = require('homey');

class WallSwitch4GangDriver extends Driver {

  async onInit() {
    await super.onInit();
    if (this._flowCardsRegistered) return;
    this._flowCardsRegistered = true;

      // === AUTO-GENERATED FLOW HANDLERS ===
      // Generated by tools/ci/generate-flow-handlers.js
      // Edit if you need custom behaviour.

      this.homey.flow.getActionCard('wall_switch_4_gang_turn_on')?.registerRunListener(async (args) => {
        if (!args.device) return false;
        await args.device.setCapabilityValue('onoff', true).catch(() => {});
        return true;
      });
      this.homey.flow.getActionCard('wall_switch_4_gang_turn_off')?.registerRunListener(async (args) => {
        if (!args.device) return false;
        await args.device.setCapabilityValue('onoff', false).catch(() => {});
        return true;
      });
      this.homey.flow.getActionCard('wall_switch_4_gang_toggle')?.registerRunListener(async (args) => {
        if (!args.device) return false;
        const v = args.device.getCapabilityValue('onoff');
        await args.device.setCapabilityValue('onoff', !v).catch(() => {});
        return true;
      });
  }
}

module.exports = WallSwitch4GangDriver;
