// Auto-generated by tools/ci/generate-flow-handlers.js — review before commit.
'use strict';

const { Driver } = require('homey');

class RgbSpotGU10Driver extends Driver {

  async onInit() {
    await super.onInit();
    if (this._flowCardsRegistered) {return;}
    this._flowCardsRegistered = true;

      // === AUTO-GENERATED FLOW HANDLERS ===
      // Generated by tools/ci/generate-flow-handlers.js
      // Edit if you need custom behaviour.

      this.homey.flow.getActionCard('rgb_spot_gu10_turn_on_85d0e')?.registerRunListener(async (args) => {
        if (!args.device) {return false;}
        await args.device.setCapabilityValue('onoff', true).catch(() => {});
        return true;
      });
      this.homey.flow.getActionCard('rgb_spot_gu10_turn_off_dc88c')?.registerRunListener(async (args) => {
        if (!args.device) {return false;}
        await args.device.setCapabilityValue('onoff', false).catch(() => {});
        return true;
      });
      this.homey.flow.getActionCard('rgb_spot_gu10_toggle_6292b')?.registerRunListener(async (args) => {
        if (!args.device) {return false;}
        const v = args.device.getCapabilityValue('onoff');
        await args.device.setCapabilityValue('onoff', !v).catch(() => {});
        return true;
      });
      this.homey.flow.getActionCard('rgb_spot_gu10_set_brightness_f5e6c')?.registerRunListener(async (args) => {
        if (!args.device) {return false;}
        await args.device.setCapabilityValue('brightness', args.brightness).catch(() => {});
        return true;
      });
      this.homey.flow.getActionCard('rgb_spot_gu10_set_color_4098b')?.registerRunListener(async (args) => {
        if (!args.device) {return false;}
        await args.device.setCapabilityValue('color', args.color).catch(() => {});
        return true;
      });
      this.homey.flow.getActionCard('rgb_spot_gu10_set_color_4098b_temperature')?.registerRunListener(async (args) => {
        if (!args.device) {return false;}
        await args.device.setCapabilityValue('color_temperature', args.temperature).catch(() => {});
        return true;
      });
  }
}

module.exports = RgbSpotGU10Driver;
