#!/usr/bin/env node
'use strict';

/**
 * INDEX - Outils divers
 * Auto-generated by UltimateProjectOrganizer
 */

const add-energy-badges = require('./add-energy-badges.js');
const add_all_pr_ids = require('./add_all_pr_ids.js');
const ADVANCED_VERIFICATION = require('./ADVANCED_VERIFICATION.js');
const analyze_all_github = require('./analyze_all_github.js');
const APPLY_DRIVER_RENAMES_SMART = require('./APPLY_DRIVER_RENAMES_SMART.js');
const APPLY_HARMONIZATION = require('./APPLY_HARMONIZATION.js');
const APP_IMAGE_GENERATOR = require('./APP_IMAGE_GENERATOR.js');
const COMPLETE_ALL_TASKS = require('./COMPLETE_ALL_TASKS.js');
const COMPLETE_POWER_AUDIT = require('./COMPLETE_POWER_AUDIT.js');
const COMPLETE_PROJECT_ENHANCEMENT = require('./COMPLETE_PROJECT_ENHANCEMENT.js');
const CONVERT_POWERSHELL_TO_NODE = require('./CONVERT_POWERSHELL_TO_NODE.js');
const CREATE_APP_IMAGES_PROFESSIONAL = require('./CREATE_APP_IMAGES_PROFESSIONAL.js');
const FINAL_PUSH_V2.1.40 = require('./FINAL_PUSH_V2.1.40.js');
const GENERATE_POWER_ICONS = require('./GENERATE_POWER_ICONS.js');
const GIT_FORCE_PUSH = require('./GIT_FORCE_PUSH.js');
const HARMONIZE_ALL_DRIVER_NAMES = require('./HARMONIZE_ALL_DRIVER_NAMES.js');
const integrate_all_ids = require('./integrate_all_ids.js');
const MASSIVE_POWER_RENAME = require('./MASSIVE_POWER_RENAME.js');
const optimize-images = require('./optimize-images.js');
const REGENERATE_ALL_CONTEXTUAL_IMAGES = require('./REGENERATE_ALL_CONTEXTUAL_IMAGES.js');
const RESIZE_IMAGES_PRESERVE_CONTENT = require('./RESIZE_IMAGES_PRESERVE_CONTENT.js');
const SAFE_GIT_COMMIT = require('./SAFE_GIT_COMMIT.js');
const UPDATE_ALL_SCRIPTS = require('./UPDATE_ALL_SCRIPTS.js');
const VERSION_SYNC_ALL = require('./VERSION_SYNC_ALL.js');

module.exports = {
  add-energy-badges,
  add_all_pr_ids,
  ADVANCED_VERIFICATION,
  analyze_all_github,
  APPLY_DRIVER_RENAMES_SMART,
  APPLY_HARMONIZATION,
  APP_IMAGE_GENERATOR,
  COMPLETE_ALL_TASKS,
  COMPLETE_POWER_AUDIT,
  COMPLETE_PROJECT_ENHANCEMENT,
  CONVERT_POWERSHELL_TO_NODE,
  CREATE_APP_IMAGES_PROFESSIONAL,
  FINAL_PUSH_V2.1.40,
  GENERATE_POWER_ICONS,
  GIT_FORCE_PUSH,
  HARMONIZE_ALL_DRIVER_NAMES,
  integrate_all_ids,
  MASSIVE_POWER_RENAME,
  optimize-images,
  REGENERATE_ALL_CONTEXTUAL_IMAGES,
  RESIZE_IMAGES_PRESERVE_CONTENT,
  SAFE_GIT_COMMIT,
  UPDATE_ALL_SCRIPTS,
  VERSION_SYNC_ALL
};
