// Auto-generated by tools/ci/generate-flow-handlers.js — review before commit.
'use strict';

const { Driver } = require('homey');

class WifiSonoffTx2chDriver extends Driver {

  async onInit() {
    await super.onInit();
    if (this._flowCardsRegistered) return;
    this._flowCardsRegistered = true;

      // === AUTO-GENERATED FLOW HANDLERS ===
      // Generated by tools/ci/generate-flow-handlers.js
      // Edit if you need custom behaviour.

      this.homey.flow.getActionCard('wifi_sonoff_tx_2ch_turn_on_gang1')?.registerRunListener(async (args) => {
        if (!args.device) return false;
        return true; // TODO: implement action for wifi_sonoff_tx_2ch_turn_on_gang1
      });
      this.homey.flow.getActionCard('wifi_sonoff_tx_2ch_turn_off_gang1')?.registerRunListener(async (args) => {
        if (!args.device) return false;
        return true; // TODO: implement action for wifi_sonoff_tx_2ch_turn_off_gang1
      });
      this.homey.flow.getActionCard('wifi_sonoff_tx_2ch_turn_on_gang2')?.registerRunListener(async (args) => {
        if (!args.device) return false;
        return true; // TODO: implement action for wifi_sonoff_tx_2ch_turn_on_gang2
      });
      this.homey.flow.getActionCard('wifi_sonoff_tx_2ch_turn_off_gang2')?.registerRunListener(async (args) => {
        if (!args.device) return false;
        return true; // TODO: implement action for wifi_sonoff_tx_2ch_turn_off_gang2
      });
      this.homey.flow.getActionCard('wifi_sonoff_tx_2ch_toggle_gang1')?.registerRunListener(async (args) => {
        if (!args.device) return false;
        const v = args.device.getCapabilityValue('onoff');
        await args.device.setCapabilityValue('onoff', !v).catch(() => {});
        return true;
      });
      this.homey.flow.getActionCard('wifi_sonoff_tx_2ch_toggle_gang2')?.registerRunListener(async (args) => {
        if (!args.device) return false;
        const v = args.device.getCapabilityValue('onoff');
        await args.device.setCapabilityValue('onoff', !v).catch(() => {});
        return true;
      });
  }
}

module.exports = WifiSonoffTx2chDriver;
