// Auto-generated by tools/ci/generate-flow-handlers.js — review before commit.
'use strict';

const { Driver } = require('homey');

class MotionSensor2Driver extends Driver {

  async onInit() {
    await super.onInit();
    if (this._flowCardsRegistered) return;
    this._flowCardsRegistered = true;

      // === AUTO-GENERATED FLOW HANDLERS ===
      // Generated by tools/ci/generate-flow-handlers.js
      // Edit if you need custom behaviour.

      this.homey.flow.getActionCard('motion_sensor_2_reset_alarm')?.registerRunListener(async (args) => {
        if (!args.device) return false;
        await args.device.setCapabilityValue('alarm', args).catch(() => {});
        return true;
      });
  }
}

module.exports = MotionSensor2Driver;
