#!/usr/bin/env node
'use strict';

/**
 * INDEX - Helpers utilitaires
 * Auto-generated by ORGANIZE_ALL_JS_FILES
 */

const BULK_OPTIMIZE_PNGS = require('./BULK_OPTIMIZE_PNGS.js');
const device-template = require('./device-template.js');
const switch-device = require('./switch-device.js');

module.exports = {
  BULK_OPTIMIZE_PNGS,
  device-template,
  switch-device
};
