// Auto-generated by tools/ci/generate-flow-handlers.js — review before commit.
'use strict';

const { Driver } = require('homey');

class RgbSpotGardenLightDriver extends Driver {

  async onInit() {
    await super.onInit();
    if (this._flowCardsRegistered) {return;}
    this._flowCardsRegistered = true;

      // === AUTO-GENERATED FLOW HANDLERS ===
      // Generated by tools/ci/generate-flow-handlers.js
      // Edit if you need custom behaviour.

      this.homey.flow.getActionCard('rgb_spot_gardenlight_turn_on_17c40')?.registerRunListener(async (args) => {
        if (!args.device) {return false;}
        await args.device.setCapabilityValue('onoff', true).catch(() => {});
        return true;
      });
      this.homey.flow.getActionCard('rgb_spot_gardenlight_turn_off_4f740')?.registerRunListener(async (args) => {
        if (!args.device) {return false;}
        await args.device.setCapabilityValue('onoff', false).catch(() => {});
        return true;
      });
      this.homey.flow.getActionCard('rgb_spot_gardenlight_toggle_824d8')?.registerRunListener(async (args) => {
        if (!args.device) {return false;}
        const v = args.device.getCapabilityValue('onoff');
        await args.device.setCapabilityValue('onoff', !v).catch(() => {});
        return true;
      });
      this.homey.flow.getActionCard('rgb_spot_gardenlight_set_brightness_4d147')?.registerRunListener(async (args) => {
        if (!args.device) {return false;}
        await args.device.setCapabilityValue('brightness', args.brightness).catch(() => {});
        return true;
      });
      this.homey.flow.getActionCard('rgb_spot_gardenlight_set_color_f8fd0')?.registerRunListener(async (args) => {
        if (!args.device) {return false;}
        await args.device.setCapabilityValue('color', args.color).catch(() => {});
        return true;
      });
      this.homey.flow.getActionCard('rgb_spot_gardenlight_set_color_f8fd0_temperature')?.registerRunListener(async (args) => {
        if (!args.device) {return false;}
        await args.device.setCapabilityValue('color_temperature', args.temperature).catch(() => {});
        return true;
      });
  }
}

module.exports = RgbSpotGardenLightDriver;
