// Auto-generated by tools/ci/generate-flow-handlers.js — review before commit.
'use strict';

const { Driver } = require('homey');

class PirMmwaveSensorDriver extends Driver {

  async onInit() {
    await super.onInit();
    if (this._flowCardsRegistered) return;
    this._flowCardsRegistered = true;

      // === AUTO-GENERATED FLOW HANDLERS ===
      // Generated by tools/ci/generate-flow-handlers.js
      // Edit if you need custom behaviour.

      this.homey.flow.getConditionCard('pir_mmwave_sensor_has_presence')?.registerRunListener(async (args) => {
        if (!args.device) return false;
        return true; // TODO: implement condition for pir_mmwave_sensor_has_presence
      });
  }
}

module.exports = PirMmwaveSensorDriver;
