#!/usr/bin/env bash
# delete-johan-comments.sh
# Generated by collect-johan-comments-to-delete.js
# DELETES all dlnraja/bot comments from JohanBendz/com.tuya.zigbee
#
# Requirements:
#   - curl + jq installed
#   - GH_TOKEN env var (or GITHUB_TOKEN) with repo scope
#
# Safety:
#   - DRY_RUN=true (default): preview only
#   - DRY_RUN=false --confirm: actually delete
#
# Usage:
#   bash delete-johan-comments.sh                              # preview (DRY_RUN=true)
#   DRY_RUN=false bash delete-johan-comments.sh --confirm      # actually delete
#   DRY_RUN=true bash delete-johan-comments.sh | head -20       # show first 20
#   DRY_RUN=true ISSUE_FILTER=1269 bash delete-johan-comments.sh  # preview only #1269

set -e

REPO="JohanBendz/com.tuya.zigbee"
DRY_RUN="${DRY_RUN:-true}"
ISSUE_FILTER="${ISSUE_FILTER:-}"
CONFIRM=false
for arg in "$@"; do
  if [ "$arg" = "--confirm" ]; then CONFIRM=true; fi
done

JSON_FILE="$(dirname "$0")/../state/johan-comments-to-delete.json"

if [ ! -f "$JSON_FILE" ]; then
  echo "ERROR: $JSON_FILE not found"
  echo "       Run: node tools/ci/collect-johan-comments-to-delete.js"
  exit 1
fi

if [ "$DRY_RUN" = "false" ] && [ "$CONFIRM" != "true" ]; then
  echo "ERROR: To actually delete, you MUST pass --confirm"
  echo ""
  echo "       DRY_RUN=true bash delete-johan-comments.sh                (preview)"
  echo "       DRY_RUN=false bash delete-johan-comments.sh --confirm    (delete ALL)"
  echo "       ISSUE_FILTER=1269 DRY_RUN=false bash delete-johan-comments.sh --confirm  (delete ONLY #1269)"
  exit 1
fi

if [ "$DRY_RUN" = "false" ]; then
  if [ -z "$GH_TOKEN" ] && [ -z "$GITHUB_TOKEN" ]; then
    echo "ERROR: GH_TOKEN or GITHUB_TOKEN must be set"
    echo "       export GH_TOKEN=ghp_***your_token***"
    exit 1
  fi
fi

TOKEN="${GH_TOKEN:-$GITHUB_TOKEN}"
TOTAL=$(jq -r '.comments | length' "$JSON_FILE")
echo "Target: $REPO"
echo "Mode: $([ "$DRY_RUN" = "true" ] && echo PREVIEW || echo DELETE)"
echo "Total comments in list: $TOTAL"
[ -n "$ISSUE_FILTER" ] && echo "Filter: only issue #$ISSUE_FILTER"
echo ""

DELETED=0
FAILED=0
SKIPPED=0

# Process each comment
jq -r '.comments[] | [.commentId, .issueNumber, .author, .createdAt, .excerpt] | @tsv' "$JSON_FILE" |
while IFS=$'\t' read -r COMMENT_ID ISSUE AUTHOR CREATED EXCERPT; do
  # Apply filter
  if [ -n "$ISSUE_FILTER" ] && [ "$ISSUE" != "$ISSUE_FILTER" ]; then
    continue
  fi
  # Truncate excerpt for display
  PREVIEW=$(echo "$EXCERPT" | cut -c1-60)

  if [ "$DRY_RUN" = "true" ]; then
    echo "  [DRY-RUN] #$ISSUE by $AUTHOR ($CREATED) id=$COMMENT_ID: $PREVIEW"
    SKIPPED=$((SKIPPED + 1))
  else
    HTTP_CODE=$(curl -sS -X DELETE \
      -H "Authorization: Bearer $TOKEN" \
      -H "Accept: application/vnd.github+json" \
      -H "X-GitHub-Api-Version: 2022-11-28" \
      -o /dev/null -w "%{http_code}" \
      "https://api.github.com/repos/$REPO/issues/comments/$COMMENT_ID" 2>/dev/null || echo "000")
    case "$HTTP_CODE" in
      204)
        echo "  ✓ Deleted #$ISSUE id=$COMMENT_ID"
        DELETED=$((DELETED + 1))
        ;;
      404)
        echo "  - Already gone: #$ISSUE id=$COMMENT_ID"
        SKIPPED=$((SKIPPED + 1))
        ;;
      401|403)
        echo "  ✗ Forbidden #$ISSUE id=$COMMENT_ID (HTTP $HTTP_CODE — not author?)"
        FAILED=$((FAILED + 1))
        ;;
      *)
        echo "  ✗ Failed #$ISSUE id=$COMMENT_ID (HTTP $HTTP_CODE)"
        FAILED=$((FAILED + 1))
        ;;
    esac
    # Rate limit protection (GitHub allows 5000 req/h, 1171 in ~6 min = safe)
    sleep 0.2
  fi
done

echo ""
echo "=== SUMMARY ==="
echo "Deleted: $DELETED"
echo "Failed : $FAILED"
echo "Skipped: $SKIPPED (already gone or DRY_RUN)"

if [ "$DRY_RUN" = "true" ]; then
  echo ""
  echo "To actually delete, run:"
  echo "  DRY_RUN=false bash tools/ci/delete-johan-comments.sh --confirm"
fi
