// Auto-generated by tools/ci/generate-flow-handlers.js — review before commit.
'use strict';

const { Driver } = require('homey');

class CurtainModule2GangDriver extends Driver {

  async onInit() {
    await super.onInit();
    if (this._flowCardsRegistered) return;
    this._flowCardsRegistered = true;

      // === AUTO-GENERATED FLOW HANDLERS ===
      // Generated by tools/ci/generate-flow-handlers.js
      // Edit if you need custom behaviour.

      this.homey.flow.getActionCard('curtain_module_2_gang_move_open_2gang')?.registerRunListener(async (args) => {
        if (!args.device) return false;
        return true; // TODO: implement action for curtain_module_2_gang_move_open_2gang
      });
      this.homey.flow.getActionCard('curtain_module_2_gang_move_close_2gang')?.registerRunListener(async (args) => {
        if (!args.device) return false;
        return true; // TODO: implement action for curtain_module_2_gang_move_close_2gang
      });
  }
}

module.exports = CurtainModule2GangDriver;
