// Auto-generated by tools/ci/generate-flow-handlers.js — review before commit.
'use strict';

const { Driver } = require('homey');

class RadiatorValveZigbeeDriver extends Driver {

  async onInit() {
    await super.onInit();
    if (this._flowCardsRegistered) return;
    this._flowCardsRegistered = true;

      // === AUTO-GENERATED FLOW HANDLERS ===
      // Generated by tools/ci/generate-flow-handlers.js
      // Edit if you need custom behaviour.

      this.homey.flow.getConditionCard('radiator_valve_zigbee_mode_is')?.registerRunListener(async (args) => {
        if (!args.device) return false;
        return true; // TODO: implement condition for radiator_valve_zigbee_mode_is
      });
      this.homey.flow.getConditionCard('radiator_valve_zigbee_is_heating')?.registerRunListener(async (args) => {
        if (!args.device) return false;
        return args.device.getCapabilityValue('heating') === true;
      });
      this.homey.flow.getActionCard('radiator_valve_zigbee_set_target_temperature')?.registerRunListener(async (args) => {
        if (!args.device) return false;
        await args.device.setCapabilityValue('target_temperature', args.temperature).catch(() => {});
        return true;
      });
      this.homey.flow.getActionCard('radiator_valve_zigbee_set_mode')?.registerRunListener(async (args) => {
        if (!args.device) return false;
        await args.device.setCapabilityValue('mode', args.mode).catch(() => {});
        return true;
      });
      this.homey.flow.getActionCard('radiator_valve_zigbee_turn_on')?.registerRunListener(async (args) => {
        if (!args.device) return false;
        await args.device.setCapabilityValue('onoff', true).catch(() => {});
        return true;
      });
      this.homey.flow.getActionCard('radiator_valve_zigbee_turn_off')?.registerRunListener(async (args) => {
        if (!args.device) return false;
        await args.device.setCapabilityValue('onoff', false).catch(() => {});
        return true;
      });
      this.homey.flow.getActionCard('radiator_valve_zigbee_toggle')?.registerRunListener(async (args) => {
        if (!args.device) return false;
        const v = args.device.getCapabilityValue('onoff');
        await args.device.setCapabilityValue('onoff', !v).catch(() => {});
        return true;
      });
      this.homey.flow.getActionCard('radiator_valve_zigbee_set_child_lock')?.registerRunListener(async (args) => {
        if (!args.device) return false;
        await args.device.setCapabilityValue('child_lock', args.enabled).catch(() => {});
        return true;
      });
      this.homey.flow.getActionCard('radiator_valve_zigbee_set_window_detection')?.registerRunListener(async (args) => {
        if (!args.device) return false;
        await args.device.setCapabilityValue('onoff', true).catch(() => {});
        return true;
      });
  }
}

module.exports = RadiatorValveZigbeeDriver;
