// Auto-generated by tools/ci/generate-flow-handlers.js — review before commit.
'use strict';

const { Driver } = require('homey');

class SirentemphumidsensorDriver extends Driver {

  async onInit() {
    await super.onInit();
    if (this._flowCardsRegistered) return;
    this._flowCardsRegistered = true;

      // === AUTO-GENERATED FLOW HANDLERS ===
      // Generated by tools/ci/generate-flow-handlers.js
      // Edit if you need custom behaviour.

      this.homey.flow.getActionCard('sirentemphumidsensor_alarm_state')?.registerRunListener(async (args) => {
        if (!args.device) return false;
        return true; // TODO: implement action for sirentemphumidsensor_alarm_state
      });
      this.homey.flow.getActionCard('sirentemphumidsensor_alarm_duration')?.registerRunListener(async (args) => {
        if (!args.device) return false;
        await args.device.setCapabilityValue('onoff', true).catch(() => {});
        return true;
      });
      this.homey.flow.getActionCard('sirentemphumidsensor_siren_volume')?.registerRunListener(async (args) => {
        if (!args.device) return false;
        return true; // TODO: implement action for sirentemphumidsensor_siren_volume
      });
      this.homey.flow.getActionCard('sirentemphumidsensor_alarm_tune')?.registerRunListener(async (args) => {
        if (!args.device) return false;
        return true; // TODO: implement action for sirentemphumidsensor_alarm_tune
      });
  }
}

module.exports = SirentemphumidsensorDriver;
