// Auto-generated by tools/ci/generate-flow-handlers.js — review before commit.
'use strict';

const { Driver } = require('homey');

class FloodSensorDriver extends Driver {

  async onInit() {
    await super.onInit();
    if (this._flowCardsRegistered) return;
    this._flowCardsRegistered = true;

      // === AUTO-GENERATED FLOW HANDLERS ===
      // Generated by tools/ci/generate-flow-handlers.js
      // Edit if you need custom behaviour.

      this.homey.flow.getConditionCard('flood_sensor_alarm_water_active')?.registerRunListener(async (args) => {
        if (!args.device) return false;
        return true; // TODO: implement condition for flood_sensor_alarm_water_active
      });
  }
}

module.exports = FloodSensorDriver;
