// Auto-generated by tools/ci/generate-flow-handlers.js — review before commit.
'use strict';

const { Driver } = require('homey');

class TunableBulbE27Driver extends Driver {

  async onInit() {
    await super.onInit();
    if (this._flowCardsRegistered) {return;}
    this._flowCardsRegistered = true;

      // === AUTO-GENERATED FLOW HANDLERS ===
      // Generated by tools/ci/generate-flow-handlers.js
      // Edit if you need custom behaviour.

      this.homey.flow.getActionCard('tunable_bulb_e27_turn_on_41220')?.registerRunListener(async (args) => {
        if (!args.device) {return false;}
        await args.device.setCapabilityValue('onoff', true).catch(() => {});
        return true;
      });
      this.homey.flow.getActionCard('tunable_bulb_e27_turn_off_bf35e')?.registerRunListener(async (args) => {
        if (!args.device) {return false;}
        await args.device.setCapabilityValue('onoff', false).catch(() => {});
        return true;
      });
      this.homey.flow.getActionCard('tunable_bulb_e27_toggle_2cf60')?.registerRunListener(async (args) => {
        if (!args.device) {return false;}
        const v = args.device.getCapabilityValue('onoff');
        await args.device.setCapabilityValue('onoff', !v).catch(() => {});
        return true;
      });
      this.homey.flow.getActionCard('tunable_bulb_e27_set_brightness_7e725')?.registerRunListener(async (args) => {
        if (!args.device) {return false;}
        await args.device.setCapabilityValue('brightness', args.brightness).catch(() => {});
        return true;
      });
      this.homey.flow.getActionCard('tunable_bulb_e27_set_color_temperature_5809d')?.registerRunListener(async (args) => {
        if (!args.device) {return false;}
        await args.device.setCapabilityValue('color_temperature', args.temperature).catch(() => {});
        return true;
      });
  }
}

module.exports = TunableBulbE27Driver;
