name: Fix Post 1558
on:
  workflow_dispatch:
jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fix post
        env:
          DISCOURSE_API_KEY: ${{ secrets.DISCOURSE_API_KEY }}
          HOMEY_EMAIL: ${{ secrets.HOMEY_EMAIL }}
          HOMEY_PASSWORD: ${{ secrets.HOMEY_PASSWORD }}
        run: node .github/scripts/fix-post-1558.js
