name: Homey App Store Publication

on:
  push:
    branches: [master, main]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install Dependencies
        run: npm ci || npm install
      
      - name: Install Homey CLI
        run: |
          npm install -g homey
          homey --version
      
      - name: Configure Homey Auth
        env:
          HOMEY_TOKEN: ${{ secrets.HOMEY_TOKEN }}
        run: |
          if [ -z "$HOMEY_TOKEN" ]; then
            echo "ERROR: HOMEY_TOKEN not configured"
            exit 1
          fi
          mkdir -p ~/.homey
          echo '{"token":"'"$HOMEY_TOKEN"'"}' > ~/.homey/.homeyrc.json
      
      - name: Clean Cache
        run: rm -rf .homeybuild .homeycompose
      
      - name: Validate App
        run: homey app validate --level=publish
      
      - name: Build App
        run: homey app build
      
      - name: Publish to App Store
        run: |
          echo "Publication avec stdin automatique..."
          
          # Methode simple avec printf et pipe
          printf "y\ny\n\nSDK3 compliance + GitHub Actions\ny\nn\n" | homey app publish || {
            echo "ERREUR: Publication echouee"
            echo "Tentative alternative..."
            
            # Alternative: Utiliser yes + timeout
            timeout 120s bash -c 'yes "" | homey app publish' || echo "Publication timeout"
          }
          
          echo "Publication completee"
      
      - name: Summary
        if: always()
        run: |
          echo "## Publication Status" >> $GITHUB_STEP_SUMMARY
          echo "**App:** Universal Tuya Zigbee" >> $GITHUB_STEP_SUMMARY
          echo "**Status:** ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
          echo "[Dashboard](https://tools.developer.homey.app/apps/app/com.dlnraja.tuya.zigbee)" >> $GITHUB_STEP_SUMMARY
