# Workflow pour désactiver GitHub Pages
# GitHub déclenche automatiquement ce workflow pour les Pages
# On le remplace par un skip explicite

name: pages-build-deployment

on:
  push:
    branches: ["master"]
  workflow_dispatch:

# Pas de permissions pour Pages
permissions:
  contents: read

jobs:
  skip-pages:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Skip GitHub Pages Build
        run: |
          echo "⏭️ GitHub Pages désactivé pour ce repository"
          echo ""
          echo "Ce repository utilise:"
          echo "- Homey App Store publication (publish-auto.yml)"
          echo "- Pas de GitHub Pages"
          echo ""
          echo "Pour désactiver complètement GitHub Pages:"
          echo "1. Aller sur: https://github.com/${{ github.repository }}/settings/pages"
          echo "2. Source: None"
          echo "3. Save"
          exit 0
