name: Close Stale Issues
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          days-before-stale: -1 # Désactivation du marquage
          days-before-close: -1 # Désactivation de la fermeture
          exempt-issues-labels: '*' # Exempte tous les tickets
