name: Validation Checks

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install ImageMagick
      run: sudo apt-get install -y imagemagick
      
    - name: Install Homey CLI
      run: npm install -g homey
      
    - name: Run pre-publish checks
      run: node scripts/validation/pre-publish-check.js
      
    - name: Validate app structure
      run: |
        homey app build
        homey app validate --level publish
