#!/usr/bin/env node
'use strict';

/**
 * INDEX - Scripts déploiement
 * Auto-generated by UltimateProjectOrganizer
 */

const GIT_FORCE_PUSH = require('./GIT_FORCE_PUSH.js');
const publish_and_promote = require('./publish_and_promote.js');
const SAFE_PUSH_AND_PUBLISH = require('./SAFE_PUSH_AND_PUBLISH.js');
const VERSION_CHECKER = require('./VERSION_CHECKER.js');
const VERSION_SYNC_ALL = require('./VERSION_SYNC_ALL.js');

module.exports = {
  GIT_FORCE_PUSH,
  publish_and_promote,
  SAFE_PUSH_AND_PUBLISH,
  VERSION_CHECKER,
  VERSION_SYNC_ALL
};
