#!/usr/bin/env node
'use strict';

/**
 * INDEX - Scripts de déploiement
 * Auto-generated by ORGANIZE_ALL_JS_FILES
 */

const ANALYZE_PUBLISHED_IMAGES = require('./ANALYZE_PUBLISHED_IMAGES.js');
const DIAGNOSE_IMAGES = require('./DIAGNOSE_IMAGES.js');
const FINAL_PUSH_V2.1.40 = require('./FINAL_PUSH_V2.1.40.js');
const GIT_FORCE_PUSH = require('./GIT_FORCE_PUSH.js');
const INTELLIGENT_NEW_PRODUCTS_2025 = require('./INTELLIGENT_NEW_PRODUCTS_2025.js');
const PUBLISH_TO_HOMEY = require('./PUBLISH_TO_HOMEY.js');
const SAFE_GIT_COMMIT = require('./SAFE_GIT_COMMIT.js');
const SAFE_PUSH_AND_PUBLISH = require('./SAFE_PUSH_AND_PUBLISH.js');
const SMART_PUBLISH = require('./SMART_PUBLISH.js');
const VERSION_CHECKER = require('./VERSION_CHECKER.js');
const commit_final = require('./commit_final.js');
const publish-homey-official = require('./publish-homey-official.js');
const publish_and_promote = require('./publish_and_promote.js');
const smart_push = require('./smart_push.js');

module.exports = {
  ANALYZE_PUBLISHED_IMAGES,
  DIAGNOSE_IMAGES,
  FINAL_PUSH_V2.1.40,
  GIT_FORCE_PUSH,
  INTELLIGENT_NEW_PRODUCTS_2025,
  PUBLISH_TO_HOMEY,
  SAFE_GIT_COMMIT,
  SAFE_PUSH_AND_PUBLISH,
  SMART_PUBLISH,
  VERSION_CHECKER,
  commit_final,
  publish-homey-official,
  publish_and_promote,
  smart_push
};
