'use strict';

const { ZigBeeDriver } = require('homey-zigbeedriver');

class ButtonWireless8Driver extends ZigBeeDriver {

  async onInit() {
    this.log('ButtonWireless8Driver initialized');
    
    // Flow cards are auto-generated by homey app build
    // No manual registration needed
  }
}

module.exports = ButtonWireless8Driver;
